auto: true

#markdown: rdiscount
highlighter: 'pygments'
#paginate: 8
permalink: /:title

title: Meierxiaojie'May
url: http://may90.github.io
feed: /atom.xml
author_info: <a href="http://may90.github.io/">May</a>
